### ISSUE TITLE
this component can not run in ionic 3.1.1,How to run on ionic 3.1.1?

### ISSUE THREAD

**Issue by TheYoungester** [raychenfj/ion-multi-picker#47]

**Comment by raychenfj** [comment]
I've updated this component to support the very initial version of ionic 3. 

But not sure what's new in 3.1.1. 

Will lookingi into it.

**Comment by TheYoungester** [comment]
Thanks！Please accept my best wishes for your happiness and success！

**Comment by sebastiansommer** [comment]
+1 Would like to use this component in ionic 3.3

**Comment by raychenfj** [comment]
@TheYoungester  @sebastiansommer 

Hi both,

Would like to know some more detail about this issuse, because when I update my demo to ionic 3.1.1, everything works fine.

So can you at least paste your log here, and is it platform specific ?

And please make sure you install 2.0.0 of this component, and update the ionic cli to latest version  as well.

**Comment by varunaaruru** [comment]
its working fine for me too..

**Comment by raychenfj** [comment]
Closed since can't reproduce. Feel free to reopen it if happens again.
